/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "stm32f103xx_gpio_driver.h"

void delay(void){
	for (uint32_t i = 0; i < 500000/2; i ++);
}


int main(void)
{
   GPIO_Handle_t GPIOxLed;
   GPIOxLed.pGPIOx = GPIOC;
   GPIOxLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
   GPIOxLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT_ALT;
   GPIOxLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_Speed_10MHz;
   GPIOxLed.GPIO_PinConfig.GPIO_PinOutPpOp = GPIO_OutPP;

   GPIO_PeriClockCtr(GPIOC, ENABLE );
   //GPIOC_PCLK_EN();

   GPIO_Init(&GPIOxLed);

   while(1){
	   GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_7);
	   delay();
   }



}
