/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "stm32f103xx_gpio_driver.h"

void delay(void){
	for (uint32_t i = 0; i < 500000; i ++);
}


int main(void)
{
   GPIO_Handle_t GPIOxLed, GPIO_Btn;
   GPIOxLed.pGPIOx = GPIOC;
   GPIOxLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
   GPIOxLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT_ALT;
   GPIOxLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_Speed_10MHz;
   GPIOxLed.GPIO_PinConfig.GPIO_PinOutPpOp = GPIO_OutPP;

   GPIO_PeriClockCtr(GPIOC, ENABLE);

   GPIO_Init(&GPIOxLed);

   GPIO_Btn.pGPIOx = GPIOC;
   GPIO_Btn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_10;
   GPIO_Btn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
   GPIO_Btn.GPIO_PinConfig.GPIO_PinInType = GPIO_InPuPd;

   GPIO_Init(&GPIO_Btn);



   //set thanh bit 10 cua thanh ghi ODR--> pull down
   GPIO_Btn.pGPIOx->GPIOx_ODR &= ~(1 <<  GPIO_Btn.GPIO_PinConfig.GPIO_PinNumber);



   while(1){

	   if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_10) == 1){
		     GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_7);
		     delay();
	   }




   }

	//RCC->RCC_APB2ENR |= (1 << 4);

}
